# Generated by Django 3.2 on 2021-04-19 11:26

import Article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='اسلاگ (نامک)')),
                ('description', models.CharField(max_length=250, verbose_name='توضیحات')),
                ('body', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(null=True, upload_to=Article.models.upload_image, verbose_name='عکس')),
                ('tags', models.CharField(max_length=250, verbose_name='تگ ها')),
                ('keywords', models.CharField(max_length=250, verbose_name='کلمات کلیدی')),
                ('status', models.IntegerField(default=0, verbose_name='وضعیت')),
                ('likeCount', models.IntegerField(default=0, verbose_name='تعداد لایک ها')),
                ('viewCount', models.IntegerField(default=0, verbose_name='تعداد بازدید ها')),
                ('commentCount', models.IntegerField(default=0, verbose_name='تعداد نظرات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
