# Generated by Django 3.2 on 2021-04-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like_And_DisLike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_and_dislike',
            name='status',
            field=models.CharField(choices=[('like', 'لایک'), ('dislike', 'دیسلایک')], max_length=10, verbose_name='نوع'),
        ),
    ]
