# Generated by Django 3.2 on 2021-04-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Like_And_DisLike', '0002_alter_like_and_dislike_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like_and_dislike',
            old_name='status',
            new_name='type',
        ),
    ]
