# Generated by Django 3.2 on 2021-05-12 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Like_And_DisLike', '0003_rename_status_like_and_dislike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_and_dislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_and_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
