# Generated by Django 3.2 on 2021-05-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0008_notifyuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payment', '0007_remove_payment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address1', models.TextField(verbose_name='آدرس 1')),
                ('address2', models.TextField(null=True, verbose_name='آدرس 2')),
                ('post_code', models.IntegerField(verbose_name='کد پستی')),
                ('payment_type', models.CharField(choices=[('online', 'آنلاین'), ('cash', 'نقدی')], max_length=6, null=True, verbose_name='نوع پرداخت')),
                ('status', models.CharField(choices=[('sending', 'درحال ارسال'), ('posted', 'ارسال شده'), ('delivered', 'تحویل داده شده')], default='sending', max_length=9, null=True, verbose_name='وضعیت ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.payment', verbose_name='پرداخت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
