# Generated by Django 3.2 on 2021-05-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_notifyuser'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.color', verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.size', verbose_name='سایز'),
        ),
    ]
