# Generated by Django 3.2 on 2021-05-07 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_auto_20210507_1519'),
        ('Order', '0002_auto_20210507_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.payment', verbose_name='پرداخت'),
        ),
    ]
