# Generated by Django 3.2 on 2021-05-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_auto_20210507_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.IntegerField(max_length=10, verbose_name='کد پستی'),
        ),
    ]
