# Generated by Django 3.2 on 2021-05-07 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_alter_order_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')], verbose_name='کد پستی'),
        ),
    ]
