# Generated by Django 3.2 on 2021-05-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_order_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=454544, max_length=11, verbose_name='موبایل'),
            preserve_default=False,
        ),
    ]
