# Generated by Django 3.2 on 2021-05-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_notifyuser'),
        ('Order', '0008_auto_20210507_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.size', verbose_name='سایز'),
        ),
    ]
