# Generated by Django 3.2 on 2021-04-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WishList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'علاقه مندی', 'verbose_name_plural': 'علاقه مندی ها'},
        ),
    ]
