# Generated by Django 3.2 on 2021-04-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_ResetPassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='آیا استفاده شده است'),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='token',
            field=models.CharField(max_length=256, unique=True, verbose_name='توکن'),
        ),
    ]
