# Generated by Django 3.2 on 2021-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_auto_20210420_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='شناسه مدل نظر'),
        ),
    ]
