# Generated by Django 3.2 on 2021-05-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0006_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='Comment.comment', verbose_name='والد'),
        ),
    ]
