# Generated by Django 3.2 on 2021-04-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_auto_20210430_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
