# Generated by Django 3.2 on 2021-04-21 17:14

import Slider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to=Slider.models.upload_image, verbose_name='عکس'),
        ),
    ]
