# Generated by Django 3.2 on 2021-04-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=255, null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(max_length=255, null=True, verbose_name='کد بازگشتی درگاه'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_code',
            field=models.CharField(max_length=255, null=True, verbose_name='شناسه پیگیری'),
        ),
    ]
