# Generated by Django 3.2 on 2021-04-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_suggestion_count'),
        ('Payment', '0005_payment_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Product.product', verbose_name='محصول'),
        ),
    ]
