# Generated by Django 3.2 on 2021-05-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_alter_payment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
    ]
