# Generated by Django 3.2 on 2021-05-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0007_remove_payment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='color',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='count',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='size',
        ),
    ]
