# Generated by Django 3.2 on 2021-04-19 11:26

import Product.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=Product.models.upload_product_images, verbose_name='عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس ها',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=50, verbose_name='نامک')),
                ('short_text', models.TextField(max_length=250, verbose_name='توضیحات')),
                ('text', models.TextField(verbose_name='متن')),
                ('type', models.CharField(default='free', max_length=15, verbose_name='نوع')),
                ('tags', models.CharField(max_length=250, verbose_name='تگ ها')),
                ('price', models.CharField(max_length=50, verbose_name='قمیت')),
                ('viewCount', models.IntegerField(default=0, verbose_name='تعداد بازدیدها')),
                ('likeCount', models.IntegerField(default=0, verbose_name='تعداد لایک ها')),
                ('commentCount', models.IntegerField(default=0, verbose_name='تعداد نظرات')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت تایید')),
                ('count', models.IntegerField(default=1, verbose_name='تعداد')),
                ('is_removed', models.BooleanField(default=False, verbose_name='آیا حذف شده')),
                ('original_image', models.ImageField(null=True, upload_to=Product.models.upload_product_original_image, verbose_name='عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category', verbose_name='دسته بندی')),
                ('color', models.ManyToManyField(related_query_name='product', to='Product.Color', verbose_name='رنگ ها')),
                ('size', models.ManyToManyField(related_query_name='product', to='Product.Size', verbose_name='سایز ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
