# Generated by Django 3.2 on 2021-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_suggestion_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='نامک'),
        ),
    ]
