# Generated by Django 3.2 on 2021-05-12 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_notifyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
